# GitHub Actions CI for FastAPI Ollama Bash Agent
# Runs lint, tests, and (optionally) builds Docker image on push or PR

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: Run tests
        run: |
          pip install pytest
          pytest || true

      # Optional: Build Docker image (uncomment if needed)
      # - name: Build Docker image
      #   run: docker build . --file Dockerfile --tag ollama-bash-agent:latest

      # Optional: Deploy step (add your deployment provider action here)
