// This file is auto-generated by the Jinja2 template engine.
// It sets window variables from server-injected JSON. Do not edit directly.

window._prompt = window._injected.prompt;
window._model = window._injected.model;
window._bash_command = window._injected.bash_command;
window._output = window._injected.output;
window._error = window._injected.error;
window._raw_model_output = window._injected.raw_model_output;
window._history = window._injected.history;
